# Generated by Django 5.1.7 on 2025-04-02 15:14

import django.db.models.deletion
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('folder', models.ForeignKey(default=files.models.get_default_folder, on_delete=django.db.models.deletion.CASCADE, related_name='the_folder_that_contains_the_file', to='folders.folder')),
            ],
        ),
    ]
